# UBCUAS Gitlab-CI configuration

image: docker

services:
  - docker:dind

variables:
  LC_ALL: 'C.UTF-8'
  LANG: 'C.UTF-8'
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build & Deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker build --tag ubcuas/uasitl:latest .
    - docker push ubcuas/uasitl:latest
