name: Docker CI

on:
  schedule:
    - cron: '0 0 * * 6'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]

jobs:
  x86:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Copy Shared Libraries
      run: bash ${GITHUB_WORKSPACE}/configure.sh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      if: true
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: x86/
        platforms: linux/amd64
        push: true
        tags: ubcuas/uasitl:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max


  arm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Copy Shared Libraries
      run: bash ${GITHUB_WORKSPACE}/configure.sh
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: arm/
        platforms: linux/arm/v7,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ubcuas/uasitl:arm
        cache-from: type=gha
        cache-to: type=gha,mode=max
