name: Docker CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      copter:
        description: 'Copter Version (#.#.#)'
        required: false
        default: ''
        type: string
      plane:
        description: 'Plane Version (#.#.#)'
        required: false
        default: ''
        type: string

# For pull request validation, build a default version of each vehicle
env:
  COPTER_VERSION: '4.5.1'
  PLANE_VERSION: '4.5.0'

jobs:
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vehicle: [ 'copter', 'plane' ]
        arch: [ 'x86', 'arm' ]
        # Exclude any vehicles where the version is not specified
        # This works since setting the version to '' causes the exclusion to match
        exclude:
          - vehicle: copter${{ inputs.copter }}
          - vehicle: vehicle${{ inputs.plane }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy Shared Libraries
      run: bash ${GITHUB_WORKSPACE}/configure.sh

    - name: Set up QEMU
      if: ${{ matrix.arch == 'arm' }}
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Configure Version
      run: |
        if [[ ${{ matrix.vehicle }} == 'copter' ]]; then
          echo "VERSION=${{ inputs.copter || env.COPTER_VERSION }}" >> $GITHUB_ENV
        else
          echo "VERSION=${{ inputs.plane || env.PLANE_VERSION }}" >> $GITHUB_ENV
        fi

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.arch }}/
        platforms: ${{ (matrix.arch == 'x86' && 'linux/amd64') || 'linux/arm/v7,linux/arm64' }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ubcuas/uasitl:${{ matrix.vehicle }}${{ matrix.arch == 'arm' && '-arm' || '' }}-${{ env.VERSION }}
        build-args: |
          VERSION=${{ env.VERSION }}
          ${{ matrix.vehicle == 'plane' && 'VEHICLE_TYPE=1' || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
